# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stem_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stem_app

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  target 'stem_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'stem_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for stem_app-tvOS

  target 'stem_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
